import { StyleSheet } from 'react-native';

export const colors = {
  background: '#0F172A',
  surface: '#1E293B',
  border: '#334155',
  highlight: '#FDE047',
  text: '#F8FAFC',
  muted: '#94A3B8',
  danger: '#EF4444',
  success: '#4ADE80',
};

export const alarmStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 24,
    paddingBottom: 120,
    paddingTop: 100,
  },
  subtitle: {
    color: colors.muted,
    textAlign: 'center',
    fontSize: 18,
    marginBottom: 30,
    lineHeight: 28,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.highlight,
    marginBottom: 10,
  },
  cardText: {
    fontSize: 18,
    color: colors.muted,
    lineHeight: 28,
  },
  photoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
  },
  thumbnail: {
    width: 60,
    height: 60,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  referenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 14,
    flexWrap: 'wrap',
  },
  refThumbWrap: {
    position: 'relative',
  },
  refRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: colors.background,
    borderRadius: 9,
  },
  refAdd: {
    width: 60,
    height: 60,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickButtons: {
    gap: 10,
  },
  pickButton: {
    backgroundColor: colors.surface,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  pickButtonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
  ringingCard: {
    backgroundColor: colors.highlight,
    borderColor: colors.highlight,
  },
  ringingTitle: {
    color: '#0F172A',
  },
  ringingText: {
    color: '#0F172A',
  },
  confirmButton: {
    backgroundColor: '#0F172A',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  confirmButtonText: {
    color: colors.highlight,
    fontSize: 16,
    fontWeight: 'bold',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 32,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  emptyText: {
    fontSize: 14,
    color: colors.muted,
    textAlign: 'center',
    marginTop: 8,
  },
  alarmRow: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.border,
  },
  alarmRowRinging: {
    borderColor: colors.highlight,
    borderWidth: 1.5,
  },
  alarmTime: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.text,
  },
  enabled: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  switchControl: {
    alignSelf: 'center',
    marginTop: 3,
  },
  deleteButton: {
    width: 31,
    height: 31,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 40,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.highlight,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.highlight,
    textAlign: 'center',
    marginBottom: 12,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  modalButton: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  modalButtonPrimary: {
    backgroundColor: colors.highlight,
    borderColor: colors.highlight,
  },
  modalButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: 'bold',
  },
  modalButtonTextPrimary: {
    color: '#0F172A',
  },
});